name: install-dependencies

jobs:
  install-dependencies:
    runs-on: ubuntu-18.04
    steps:
      - uses: r-lib/actions/setup-r@master
      - name: Install remotes
        run: |
          install.packages(
            "remotes",
            repos = c("CRAN" = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest")
          )
        shell: Rscript {0}
      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install workflow dependencies
        run: |
          install.packages(
            c("renv", "rcmdcheck"),
            repos = c("CRAN" = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest")
          )
        shell: Rscript {0}
      - name: Restore dependencies from renv lockfile
        run: |
          renv::restore(
            repos = c("CRAN" = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest")
          )
        shell: Rscript {0}
